# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='consume_location',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس تحویل'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('in_shop', 'در فروشگاه'), ('take_away', 'بیرون بر')], default='in_shop', max_length=20, null=True, verbose_name='نحوه تحویل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'در انتظار'), ('preparation', 'در حال آماده سازی'), ('ready', 'آماده شده'), ('delivered', 'تحویل داده شده')], default='waiting', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='milk',
            field=models.CharField(blank=True, choices=[('skim', 'کف - کم'), ('semi', 'نصف - متوسط'), ('whole', 'کامل - زیاد')], help_text='Latte', max_length=20, null=True, verbose_name='شیر'),
        ),
    ]
